### ISSUE TITLE
Latest angular uses ng-hide class and not display attribute

### ISSUE THREAD

**Issue by Wilt** [larsthorup/angular-view#1]
The latest angular versions uses ng-hide class and not display attribute for hiding elements.
This means these tests work maybe fine with the implemented angular.js version, but when people use this repository for learning how to test with newer versions the tests will fail.

For latest angular the code should be updated as such:

        it('should connect the div', function () {
            var div = formElement.find('div');
            expect(div.attr('class')).toBe('ng-hide');
        });

        it('should connect the button with the div', function () {
            var button = formElement.find('button');
            button.trigger('click');

            var div = formElement.find('div');
            expect(div.attr('class')).toBe('');
        });

Tested with AngularJS v1.5.0

**Comment by larsthorup** [comment]
@Wilt Thank you for bringing this to my attention. May I ask you to help me out and create a pull request that brings this repo up to AngularJS v1.5.0?
